sudo: required

language: python

services: docker

before_install:
    - docker-compose up -d --build
    - docker login -u "$HEROKU_USERNAME" -p "$HEROKU_API_KEY" registry.heroku.com

script:
    - docker-compose exec python-visualization zsh -c "python src/app.py"
    - docker-compose stop

deploy:
    provider: script
    script:
        docker build -t registry.heroku.com/$HEROKU_APP_NAME/dash -f Dockerfile.prod;
        docker push registry.heroku.com/$HEROKU_APP_NAME/dash;
        heroku run --app $HEROKU_APP_NAME;
    on:
        branch:master
